version: '3.1'

services:
  server:
    build:
      context: ./node
    environment:
      - MODE=${MODE}
    container_name: server-node
    image: node
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 9222:9222
    volumes:
      - ./src:/src
    working_dir: '/src'
    depends_on:
      - db
    links:
      - db

  client:
    build:
      context: ./nginx
    container_name: static-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/usr/share/nginx/nginx.conf
      - ./static/build:/usr/share/nginx/html

  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: documents
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
